#!/bin/bash

# This script is exectued in the host environment,
# before the VS Code dev-container build.

CONTAINER_TOOL="docker"
CONTAINER_TAG=$(cat .devcontainer/devcontainer.json | grep "linux.elektrobit.com" | awk -F ":" '{print $3}' | awk -F "\"" '{print $1}')

echo "Setting EBcL workspace up..."
echo "Using EBcL container ${CONTAINER_TAG}."

# Test if docker image is available
if [ -z "$(docker images -q "linux.elektrobit.com/ebcl/sdk:${CONTAINER_TAG}")" ]; then
    if [ -z "${EBCL_CONTAINER_URL}" ]; then
        EBCL_CONTAINER_URL="http://linux.elektrobit.com/images"
    fi
    $CONTAINER_TOOL import "${EBCL_CONTAINER_URL}/ebcl_dev_container_${CONTAINER_TAG}.tar.xz" "linux.elektrobit.com/ebcl/sdk:${CONTAINER_TAG}"
else
    echo "Dev container image "linux.elektrobit.com/ebcl/sdk:${CONTAINER_TAG}" is available."
fi
