= The Boot Generator

NOTE: Many commands run by the _boot_generator_ are executed using _sudo_.
  The environment is expected to allow running _sudo_ without password.
  This is done to avoid access right issues, but a better solution may be possible.

The _boot_generator_ is responsible for preparing the kernel and bootloader binaries.
The _boot_generator_ supports the following options:

[source,bash]
----
=========================
EBcL Boot Generator 1.3.5
=========================

usage: boot_generator [-h] config_file output

Create the content of the boot partition.

positional arguments:
  config_file  Path to the YAML configuration file
  output       Path to the output directory

options:
  -h, --help   show this help message and exit
----

== Parameters

The _boot_generator_ supports the following configuration parameters:

base:: Parent configuration file. If specified, the values from the parent
  file will be used if not otherwise specified in the current file.
arch (default: arm64):: The CPU architecture of the target hardware.
  The supported values are arm64, amd64 and armhf.
use_fakeroot (default: False):: Use fakeroot in the generator tools where possible,
  instead of sudo and chroot. This may cause issues for edge-cases.
apt_repos (default: None):: A list of apt repositories to download the required Debian packages.
  In addition, an armored public key file or URL can be given as “key”, and a unarmored gpg file
  can be given as “gpg”, to authenticate the package sources. Example:

[source,yaml]
----
apt_repos:
  - apt_repo: http://archive.ubuntu.com/ubuntu
    distro: jammy
    components:
      - main
      - universe
  - apt_repo: http://archive.ubuntu.com/ubuntu
    distro: jammy-security
    components:
      - main
      - universe
----

use_ebcl_apt (default: No):: If yes, the public apt repository of _EB corbos Linux_ will be added.
  By default, the latest release will be used if the _ebcl_version_ parameter is not given.
  This is a convenience feature, but be aware that this public apt repository doesn’t provide
  customer specific or proprietary packages.
ebcl_version (default: latest release):: EB corbos Linux release version,
  for the automatically generated apt repository.
host_files (default: None):: Files to include from the host or container environment.
  The destination is the path in the target root filesystem or chroot environment.
  In addition, the parameters _mode_, to specify the mode of the file,
  _uid_, to specify the owner of the file, and _gid_, to specify the owning group
  of the file, can be used. Example:

[source,yaml]
----
host_files:
  - source: bootargs-overlay.dts
    destination: boot
  - source: bootargs.its
    destination: boot
----

files (default: None):: Files to get as result from the chroot environment.
  These files can be part of an extracted Debian package, or result of
  a script executed in the chroot environment. Example:

[source,yaml]
----
files:
  - boot/vmlinuz*
  - boot/config*
----

scripts (default: None):: The scripts which shall be executed.
  The supported environments are _chroot_, to run the script in a chroot environment,
  _fake_, to run the script in a fakeroot environment,
  _sudo_ to run the script with root privileges,
  or _shell_ to run the script in a plain shell environment.
  For _chroot_ the script will be placed at _/_ and executed from this folder.
  For all other environments, the current work directory will be the folder
  containing the target environment. In addition, parameters which are forwarded
  to the script can be provided as _params_.

[source,yaml]
----
scripts:
  - name: config_root.sh
    env: chroot
----

name (default: root):: A name which is used in the filenames of the generated artifacts.
download_deps (default: True):: Download the dependencies of the specified packages.
  This parameter must be True, to use e.g. a meta-package for the kernel binary and modules.
base_tarball (default: None): A optional base chroot environment used for generating the
  Soc specific bootloader and kernel binaries.
packages (default: None):: A list of packages. These packages will be downloaded and extracted
  to get the kernel binary.
kernel (default: None):: Name of the kernel package. This package is added to the list of packages
  which are downloaded and extracted as script environment and to get the needed binaries.
tar (default: True):: Flag for packing the boot artifacts as a tarball.
  If _embdgen_ is used to write the artifacts to an image, this will preserve the owner and
  mode of the artifacts.

== Environment variables

The _boot_generator_ makes use of the following environment variables:

EBCL_REPO_URL:: Overwrites the apt repository URL used by _use_ebcl_apt_.
EBCL_REPO_KEY:: Overwrites the apt repository armored public key used by _use_ebcl_apt_.
EBCL_REPO_GPG:: Overwrites the apt repository de-armored key used by _use_ebcl_apt_.
EBCL_VERSION:: Overwrites the EB corbos Linux version used by _use_ebcl_apt_.
LOG_LEVEL:: Sets the log-level for all tools.
RELEASE_VERSION:: Sets the EB corbos Linux SDK version used by some info texts.

== Dependencies

=== System packages

The _boot_generator_ has the following system tool dependencies:

coreutils (commands _mkdir_, _cp_, _echo_, _rm_, _chown_, _mv_, _mknod_):: Common commandline tools.
bash:: GNU Bourne Again SHell.
rsync:: A file-copying tool, used for merging folders.
tar:: GNU version of the tar archiving utility.

=== Python packages

The _boot_generator_ has the following Python package dependencies:

requests:: Used in common code to download the apt configuration and
  the apt repository keys.
pyyaml:: Used in common code for parsing the _yaml_ configuration files.
jsonpickle:: Used in the common code for storing the cache state.
unix_ar::  Used in the common code for extracting the Debian packages.
zstandard:: Used in the common code for extracting the Debian packages.

== Implementation details

The core part of the _boot_generator_ is implemented in _ebcl/tools/boot/boot.py_.
The _main_ function takes care of parsing the command line parameters
and then runs _create_boot_ of the _BootGenerator_ class, and finally runs
_finalize_ to cleanup temporary artifacts.

The build process implemented in _create_boot_ executes the following high level steps:

- Download and extract the additionally specified packages.
- If _base_tarball_: Extract the base tarball over the prepared environment.
- Copy the _host_files_ over the prepared environment.
- Execute the specified scripts.
- Copy the specified result files to the output folder.
- If pack as tar: Pack the output folder.

