= Changelog

All notable changes to this project will be documented in this file.

The format is based on https://keepachangelog.com/en/1.1.0/[Keep a Changelog]
and this project adheres to https://semver.org/[Semantic Versioning].

== [unreleased] - yyyy-mm-dd

=== Added

=== Changed

=== Fixed


== [2.0.0] - 2024-12-19

This is the first release of my fork, and will cleanup legacy parts of the
build tools I don't want to support. In addition, I finally added the support
for flat repositories.

=== Added

- _Antora_ documentation for build tools.
- _build_tools_core_ for host dependency setup.
- Support for OBS flat apt repositories.

=== Changed

- Move documentation form _mdbook_ to _Antora_.

=== Fixed


== [1.3.5] - 2025-12-17

Forking off from https://github.com/Elektrobit/ebcl_build_tools[EBcL build tools].
The EBcL build tools are developed in lock step with
https://www.elektrobit.com/products/ecu/eb-corbos/linux-built-on-ubuntu/[Elektrobit corbos Linux],
and need to follow a strict development process. This fork is my "playground"
to try out new ideas, and build images for my BeagleBone SBCs.

