= The Downloader

NOTE: Many commands run by the _boot_generator_ are executed using _sudo_.
  The environment is expected to allow running _sudo_ without password.
  This is done to avoid access right issues, but a better solution may be possible.

The _package_downloader_ is a helper tool which allows downloading and extracting
a set of Debian packages for local inspection. It supports the following options:

[source,bash]
----
=============================
EBcL Package downloader 1.3.5
=============================

usage: package_downloader [-h] [-o OUTPUT] [-a ARCH] [-d] config packages

Download and extract the given packages.

positional arguments:
  config                Path to the YAML configuration file containing the apt repository config.
  packages              List of packages separated by space.

options:
  -h, --help            show this help message and exit
  -o OUTPUT, --output OUTPUT
                        Path to the output directory
  -a ARCH, --arch ARCH  Architecture of the packages.
  -d, --download-depends
                        Download all package dependencies recursive.
----

== Parameters

The _package_downloader_ supports the following configuration parameters:

base:: Parent configuration file. If specified, the values from the parent
  file will be used if not otherwise specified in the current file.
arch (default: arm64):: The CPU architecture of the target hardware.
  The supported values are arm64, amd64 and armhf.
use_fakeroot (default: False):: Use fakeroot in the generator tools where possible,
  instead of sudo and chroot. This may cause issues for edge-cases.
apt_repos (default: None):: A list of apt repositories to download the required Debian packages.
  In addition, an armored public key file or URL can be given as “key”, and a unarmored gpg file
  can be given as “gpg”, to authenticate the package sources. Example:

[source,yaml]
----
apt_repos:
  - apt_repo: http://archive.ubuntu.com/ubuntu
    distro: jammy
    components:
      - main
      - universe
  - apt_repo: http://archive.ubuntu.com/ubuntu
    distro: jammy-security
    components:
      - main
      - universe
----

use_ebcl_apt (default: No):: If yes, the public apt repository of _EB corbos Linux_ will be added.
  By default, the latest release will be used if the _ebcl_version_ parameter is not given.
  This is a convenience feature, but be aware that this public apt repository doesn’t provide
  customer specific or proprietary packages.
ebcl_version (default: latest release):: EB corbos Linux release version,
  for the automatically generated apt repository.

== Environment variables

The _package_downloader_ makes use of the following environment variables:

EBCL_REPO_URL:: Overwrites the apt repository URL used by _use_ebcl_apt_.
EBCL_REPO_KEY:: Overwrites the apt repository armored public key used by _use_ebcl_apt_.
EBCL_REPO_GPG:: Overwrites the apt repository de-armored key used by _use_ebcl_apt_.
EBCL_VERSION:: Overwrites the EB corbos Linux version used by _use_ebcl_apt_.
LOG_LEVEL:: Sets the log-level for all tools.
RELEASE_VERSION:: Sets the EB corbos Linux SDK version used by some info texts.

== Dependencies

=== System packages

The _package_downloader_ has the following system tool dependencies:

coreutils (commands _mkdir_, _cp_, _echo_, _rm_, _chown_, _mv_, _mknod_):: Common commandline tools.
bash:: GNU Bourne Again SHell.
rsync:: A file-copying tool, used for merging folders.
tar:: GNU version of the tar archiving utility.

=== Python packages

The _package_downloader_ has the following Python package dependencies:

requests:: Used in common code to download the apt configuration and
  the apt repository keys.
pyyaml:: Used in common code for parsing the _yaml_ configuration files.
jsonpickle:: Used in the common code for storing the cache state.
unix_ar::  Used in the common code for extracting the Debian packages.
zstandard:: Used in the common code for extracting the Debian packages.

== Implementation details

The core part of the _package_downloader_ is implemented in
_ebcl/tools/downloader/downloader.py_.
The _main_ function takes care of parsing the command line parameters
and then runs _download_packages_ of the _PackageDownloader_ class.

The package download implemented in _download_packages_ makes use of the
common functions to download and extract the chosen packages.
